version: 2


models:
  - name: fact_payment
    description: "A starter dbt model"
    columns:
      - name: payment_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: fact_rental
    description: "A starter dbt model"
    columns:
      - name: rental_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null


sources:
  - name: stg2
    database: postgres
    schema: stg2
    tables:
      - name: inventory
        identifier: inventory
      - name: rental
        identifier: rental
      - name: payment
        identifier: payment