
version: 2 

models:
  - name: dim_customer_new
    description: "Customer dimension model"
    config:
      post_hook: "insert into {{this}}(customer_id, first_name, last_name) VALUES (-1, 'NA', 'NA')" 
    columns:
      - name: customer_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
    
  - name: dim_staff
    description: "Staff dimension model"
    config:
      post_hook: "insert into {{this}}(staff_id, first_name, last_name) VALUES (-1, 'NA', 'NA')"
    columns:
      - name: staff_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: dim_store
    description: "Store dimension model"
    config:
      post_hook: "insert into {{this}}(store_id, first_name, last_name) VALUES (-1, 'NA', 'NA')"
    columns:
      - name: store_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: dim_film
    description: "Film dimension model"
    config:
      post_hook: "insert into {{this}}(film_id, title, description) VALUES (-1, 'NA', 'NA')"
    columns:
      - name: film_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null


sources: 
  - name: stg2
    database: postgres
    schema: stg2
    tables: 
      - name: customer
        identifier: customer 
      - name: address
        identifier: address 
      - name: city
        identifier: city
      - name: country
        identifier: country
      - name: staff
        identifier: staff
      - name: film
        identifier: film
